Repository endless-sky/endless-sky-high-dpi, pull requests merged in 2022-09, with the labels that each got.

#257 Add high dpi assets for the "Smew"
  copyright
  images/ship/smew@2x.png
  images/thumbnail/smew@2x.png
Labels: Content

#297 fix(content): Remnant: Modified Dromedary names in the copyright
  copyright
Labels: bug

#298 fixed libpng issues in smew and ember tear images
  images/outfit/ember tear@2x.png
  images/ship/smew@2x.png
  images/thumbnail/smew@2x.png
Labels: bug

#276 Korath Exiles Expansion - Stage II 2x Sprites
  copyright
  images/hardpoint/firestorm battery@2x.png
  images/icon/firestorm torpedo@2x.png
  images/outfit/firestorm battery@2x.png
  images/outfit/firestorm torpedo rack@2x.png
  images/outfit/firestorm torpedo@2x.png
  images/outfit/large efreti steering@2x.png
  images/outfit/large efreti thruster@2x.png
  images/outfit/medium efreti steering@2x.png
  images/outfit/medium efreti thruster@2x.png
  images/outfit/small efreti steering@2x.png
  images/outfit/small efreti thruster@2x.png
  images/outfit/tiny efreti steering@2x.png
  images/outfit/tiny efreti thruster@2x.png
  images/projectile/firestorm torpedo~0@2x.png
  images/projectile/firestorm torpedo~1@2x.png
  images/projectile/firestorm torpedo~2@2x.png
  images/projectile/firestorm torpedo~3@2x.png
  images/ship/arch-carrack@2x.png
  images/ship/charm-shallop@2x.png
  images/ship/echo-galleon@2x.png
  images/ship/korsmanath a-awoj@2x.png
  images/ship/world-ship a@2x.png
  images/ship/world-ship b@2x.png
  images/ship/world-ship c@2x.png
  images/ship/world-ship d@2x.png
  images/ship/world-ship e@2x.png
  images/ship/world-ship f@2x.png
  images/thumbnail/arch-carrack@2x.png
  images/thumbnail/charm-shallop@2x.png
  images/thumbnail/echo-galleon@2x.png
  images/thumbnail/korsmanath a-awoj@2x.png
  images/thumbnail/world-ship a@2x.png
  images/thumbnail/world-ship b@2x.png
  images/thumbnail/world-ship c@2x.png
  images/thumbnail/world-ship d@2x.png
  images/thumbnail/world-ship e@2x.png
  images/thumbnail/world-ship f@2x.png
Labels: Content

#302 Add remodels of the Photovoltaic outfits
  copyright
  images/outfit/small photovoltaic@2x.png
  images/outfit/tiny photovoltaic@2x.png
Labels: Updating
